# docker compose --profile $COMPOSE_PROFILES config --services | sort
include:

  # simulation
  - carla-simulation/docker-compose.yml
  - sumo-simulation/docker-compose.yml

  # stack
  - openadstack/docker-compose.yml

  # utils
  - utils/gui/docker-compose.yml
