services:

  sumo-interface:
    profiles:
      - sumo
    extends:
      file: ../openadstack/openadstack/utils/compose/docker-compose.template.yml
      service: ros2-gpu-x11-service
    image: ghcr.io/openads-project/sumo_interface:v1.1.0
    ports:
      - 8813:8813
    environment:
      NAMESPACE: /sumo
      # params
      MANUAL_CONTROL_ENABLED: true
      MAP: ${MAP}
      SPAWN_POINT: ${SPAWN_POINT}
      # inputs
      CONTROLS_TOPIC: /control/ackermann_trajectory_control/controls
      # outputs
      EGO_DATA_TOPIC: ~/ego_data
      GLOBAL_OBJECT_LIST_TOPIC: ~/global_object_list
      MAP_INFO_TOPIC: ~/map_info
      OBJECT_LIST_TOPIC: ~/object_list
      GNSS_TOPIC: ~/gnss
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch sumo_interface sumo_interface.launch.py \
          namespace:=$${NAMESPACE} \
          manual_control_enabled:=$${MANUAL_CONTROL_ENABLED} \
          map:=$${MAP} \
          ego_spawn_pose:=$${SPAWN_POINT} \
          controls_automated_topic:=$${CONTROLS_TOPIC} \
          ego_data_topic:=$${EGO_DATA_TOPIC} \
          global_object_list_topic:=$${GLOBAL_OBJECT_LIST_TOPIC} \
          object_list_topic:=$${OBJECT_LIST_TOPIC} \
          map_info_topic:=$${MAP_INFO_TOPIC} \
          gnss_topic:=$${GNSS_TOPIC}
    volumes:
      - ./config/sumo_interface/params.yml:/docker-ros/ws/install/sumo_interface/share/sumo_interface/config/params.yml
   
  sumo-simulation-adapter:
    profiles:
      - sumo
    depends_on:
      - sumo-interface
    extends:
      file: ../openadstack/openadstack/utils/compose/docker-compose.template.yml
      service: ros2-service
    image: ghcr.io/openads-project/simulation_adapter:v1.4.1
    environment:
      NAMESPACE: /sumo
      NAME: simulation_adapter
      # inputs
      INPUT_EGO_DATA_TOPIC: /sumo/sumo_interface/ego_data
      INPUT_MAP_INFO_TOPIC: /sumo/sumo_interface/map_info
      INPUT_OBJECT_LIST_TOPIC: /sumo/sumo_interface/object_list
      INPUT_TRAJECTORY_TOPIC: /planning/trajectory_optimization/trajectory
      # outputs
      OUTPUT_EGO_DATA_TOPIC: /localization/ego_state_estimation/ego_data
      OUTPUT_EGO_IMU_TOPIC: /simulation/imu
      OUTPUT_EGO_ODOMETRY_TOPIC: /simulation/odometry
      OUTPUT_EGO_VEHICLE_STATE_TOPIC: /simulation/vehicle_state
      OUTPUT_OBJECT_LIST_TOPIC: /simulation/object_list
      OUTPUT_OBJECT_LIST_FIXED_TOPIC: /simulation/object_list_fixed
      # other
      LOG_LEVEL: ${LOG_LEVEL:-info}
      USE_SIM_TIME: ${USE_SIM_TIME:-true}
      PARAMS: ${PARAMS:-/docker-ros/ws/install/simulation_adapter/share/simulation_adapter/config/params.yml}
      LOAD_LANELET_MAP: ${LANELET_RELOAD:-true}
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch simulation_adapter simulation_adapter.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          log_level:=$${LOG_LEVEL} \
          use_sim_time:=$${USE_SIM_TIME} \
          params:=$${PARAMS} \
          load_lanelet_map:=$${LOAD_LANELET_MAP} \
          input_map_info_topic:=$${INPUT_MAP_INFO_TOPIC} \
          input_ego_data_topic:=$${INPUT_EGO_DATA_TOPIC} \
          input_object_list_topic:=$${INPUT_OBJECT_LIST_TOPIC} \
          input_trajectory_topic:=$${INPUT_TRAJECTORY_TOPIC} \
          output_ego_data_topic:=$${OUTPUT_EGO_DATA_TOPIC} \
          output_object_list_topic:=$${OUTPUT_OBJECT_LIST_TOPIC} \
          output_object_list_fixed_topic:=$${OUTPUT_OBJECT_LIST_FIXED_TOPIC} \
          output_ego_imu_topic:=$${OUTPUT_EGO_IMU_TOPIC} \
          output_ego_odometry_topic:=$${OUTPUT_EGO_ODOMETRY_TOPIC} \
          output_ego_vehicle_state_topic:=$${OUTPUT_EGO_VEHICLE_STATE_TOPIC}
    volumes:
      - ./config/simulation_adapter/params.yml:/docker-ros/ws/install/simulation_adapter/share/simulation_adapter/config/params.yml
