services:

  planning.lanelet2-route-planning:
    profiles:
      - planning
      - ml-planning
    extends:
      file: ../../openadstack/planning/lanelet2_route_planning/docker-compose.yml
      service: planning.lanelet2-route-planning
    environment:
      PARAMS: /params.yml
    volumes:
      - ./params.yml:/params.yml

  planning.plan-route-action-client:
    profiles:
      - planning
      - ml-planning
    extends:
      file: ../../openadstack/utils/compose/docker-compose.template.yml
      service: ros2-service
    image: ghcr.io/openads-project/lanelet2_route_planning:latest
    command:
      - /bin/bash
      - -ic
      - |
        ros2 run plan_route_action_client plan_route_action_client \
          --ros-args \
          --params-file /params.yml
    volumes:
      - ./params.plan-route-action-client.yml:/params.yml
