/**/*:
  ros__parameters:
    ll2_map_server_name: /localization/lanelet2_map_server
    waypoints:
      - "50.787524, 6.050095, -1"
      - "50.779794, 6.050634, -1"
      - "50.784935, 6.043669, -1"
      - "50.787801, 6.046555"
    enable_random_destination: false
    enable_continuous_planning: true
    continuous_planning_replanning_proportion: 0.6
    cancel_route: false
