# Remote compose file with overrides defined here can be rendered by
# `openadstack/openadstack/utils/scripts/render_compose_sources.py --root-dir carla-simulation`

include:
  - oci://ghcr.io/openads-project/monitoring:compose-v26.9.4

services:

  monitoring:
    profiles:
      - carla
    depends_on:
      - carla-manual-control
    restart: unless-stopped # requires incoming topic
    extends:
      file: ../../openadstack/openadstack/utils/compose/docker-compose.template.yml
      service: ros2-service
    environment:
      NAMESPACE: /
      NAME: carla_control_active_bridge
    command: >
      ros2 run topic_tools transform
        /carla/ego_vehicle/vehicle_control_manual_override
        /control/active
        std_msgs/Bool
        "std_msgs.msg.Bool(data=not m.data)"
        --import std_msgs
