environments:
  default:
    values:
      - environments/profiles.yaml.gotmpl
      - environments/base.yaml.gotmpl
      - environments/overrides.yaml.gotmpl

---
releases:
# carla-simulation
- name: carla-ackermann-control
  chart: oci://ghcr.io/openads-project/carla-ros-bridge/helm/carla-ackermann-control
  version: 0.10.0-1.1.0-carla-ackermann-control-update-deployment
  condition: profileGroups.carla.enabled
  values: [carla-simulation/carla-ackermann-control/values.yaml.gotmpl]
- name: carla-control-active-bridge
  chart: oci://ghcr.io/openads-project/monitoring/helm/monitoring
  version: 26.9.4
  condition: profileGroups.carla.enabled
  values: [carla-simulation/carla-control-active-bridge/values.yaml.gotmpl]
- name: carla-converter
  chart: oci://ghcr.io/openads-project/carla_converter/helm/carla-converter
  version: 1.3.1-main
  condition: profileGroups.carla.enabled
  values: [carla-simulation/carla-converter/values.yaml.gotmpl]
- name: carla-environment
  chart: oci://REPLACE_ME/carla-scenario-runner-ros
  version: REPLACE_ME
  condition: profileGroups.traffic.enabled
  values: [carla-simulation/carla-environment/values.yaml.gotmpl]
- name: carla-manual-control
  chart: oci://ghcr.io/openads-project/carla-ros-bridge/helm/carla-manual-control
  version: 0.10.0-1.1.0-carla-manual-control-update-deployment
  condition: profileGroups.carla.enabled
  values: [carla-simulation/carla-manual-control/values.yaml.gotmpl]
- name: carla-ros-bridge
  chart: oci://ghcr.io/openads-project/carla-ros-bridge/helm/carla-ros-bridge
  version: 0.10.0-1.1.0-carla-ros-bridge-update-deployment
  condition: profileGroups.carla.enabled
  values: [carla-simulation/carla-ros-bridge/values.yaml.gotmpl]
- name: carla-scenario-runner-ros-automated-testing
  chart: oci://REPLACE_ME/carla-scenario-runner-ros
  version: REPLACE_ME
  condition: profileGroups.automated-testing.enabled
  values: [carla-simulation/carla-scenario-runner-ros-automated-testing/values.yaml.gotmpl]
- name: carla-scenario-runner-ros-manual-testing
  chart: oci://REPLACE_ME/carla-scenario-runner-ros
  version: REPLACE_ME
  condition: profileGroups.manual-testing.enabled
  values: [carla-simulation/carla-scenario-runner-ros-manual-testing/values.yaml.gotmpl]
- name: carla-server
  chart: oci://ghcr.io/openads-project/carla-simulator/helm/carla-simulator
  version: 0.1.0-helm
  condition: profileGroups.carla.enabled
  values: [carla-simulation/carla-server/values.yaml.gotmpl]
- name: carla-simulation-adapter
  chart: oci://ghcr.io/openads-project/simulation_adapter/helm/simulation-adapter
  version: 1.4.1-main
  condition: profileGroups.carla.enabled
  values: [carla-simulation/carla-simulation-adapter/values.yaml.gotmpl]
- name: carla-spawn-objects
  chart: oci://ghcr.io/openads-project/carla-ros-bridge/helm/carla-spawn-objects
  version: 0.10.0-1.1.0-carla-spawn-objects-update-deployment
  condition: profileGroups.carla.enabled
  values: [carla-simulation/carla-spawn-objects/values.yaml.gotmpl]
- name: ros-middleware-bridge
  chart: oci://ghcr.io/openads-project/ros_middleware_bridge/helm/ros-middleware-bridge
  version: 1.2.1-main
  condition: profileGroups.carla.enabled
  values: [carla-simulation/ros-middleware-bridge/values.yaml.gotmpl]
# openadstack
- name: ackermann-trajectory-control
  chart: oci://ghcr.io/openads-project/ackermann_trajectory_control/helm/ackermann-trajectory-control
  version: 1.5.0-main
  condition: profileGroups.ml-planning-or-planning.enabled
  values: [openadstack/control/ackermann_trajectory_control/values.yaml.gotmpl]
- name: robot-state-publisher
  chart: oci://ghcr.io/openads-project/monitoring/helm/monitoring
  version: 1.0.0-main
  values: [openadstack/essentials/robot-state-publisher/values.yaml.gotmpl]
- name: triton-server
  chart: oci://ghcr.io/openads-project/openads-helm/triton-server
  version: 26.05
  condition: profileGroups.ml-planning-or-perception.enabled
  values: [openadstack/essentials/triton-server/values.yaml.gotmpl]
- name: zenoh-router
  chart: oci://ghcr.io/openads-project/openads-helm/zenoh-router
  version: 0.2.10
  values: [openadstack/essentials/zenoh-router/values.yaml.gotmpl]
- name: lanelet2-map-server
  chart: oci://ghcr.io/openads-project/lanelet2_map_server/helm/lanelet2-map-server
  version: 1.2.2-main
  values: [openadstack/localization/lanelet2_map_server/values.yaml.gotmpl]
- name: bag-recorder
  chart: oci://ghcr.io/openads-project/monitoring/helm/monitoring
  version: 1.0.0-main
  condition: profileGroups.bag-recording.enabled
  values: [openadstack/monitoring/bag-recorder/values.yaml.gotmpl]
- name: rviz-carla
  chart: oci://ghcr.io/openads-project/monitoring/helm/monitoring
  version: 1.0.0-main
  condition: profileGroups.carla.enabled
  values: [openadstack/monitoring/rviz-carla/values.yaml.gotmpl]
- name: point-cloud-fusion
  chart: oci://ghcr.io/openads-project/point_cloud_fusion/helm/point-cloud-fusion
  version: 1.4.0-main
  condition: profileGroups.perception.enabled
  values: [openadstack/perception/point_cloud_fusion/values.yaml.gotmpl]
- name: point-cloud-object-detection
  chart: oci://ghcr.io/openads-project/point_cloud_object_detection/helm/point-cloud-object-detection
  version: 3.0.0-main
  condition: profileGroups.perception.enabled
  values: [openadstack/perception/point_cloud_object_detection/values.yaml.gotmpl]
- name: lanelet2-route-planning
  chart: oci://ghcr.io/openads-project/lanelet2_route_planning/helm/lanelet2-route-planning
  version: 1.2.0-main
  condition: profileGroups.ml-planning-or-planning.enabled
  values: [openadstack/planning/lanelet2_route_planning/values.yaml.gotmpl]
- name: simple-planner
  chart: oci://ghcr.io/openads-project/simple_planner/helm/simple-planner
  version: 1.4.0-main
  condition: profileGroups.ml-planning-or-planning.enabled
  values: [openadstack/planning/simple_planner/values.yaml.gotmpl]
- name: trajectory-optimization
  chart: oci://ghcr.io/openads-project/trajectory_optimization/helm/trajectory-optimization
  version: 1.4.0-main
  condition: profileGroups.ml-planning-or-planning.enabled
  values: [openadstack/planning/trajectory_optimization/values.yaml.gotmpl]
- name: autoware-multi-object-tracker
  chart: oci://ghcr.io/thinking-cars/autoware_multi_object_tracker/helm/autoware-multi-object-tracker
  version: 1.1.0-main
  condition: profileGroups.perception.enabled
  values: [openadstack/understanding/autoware_multi_object_tracker/values.yaml.gotmpl]
- name: lanelet2-object-list-prediction-no-perception
  chart: oci://ghcr.io/openads-project/lanelet2_object_list_prediction/helm/lanelet2-object-list-prediction
  version: 1.0.2-main
  condition: profileGroups.no-perception.enabled
  values: [openadstack/understanding/lanelet2_object_list_prediction/lanelet2-object-list-prediction-no-perception/values.yaml.gotmpl]
- name: lanelet2-object-list-prediction-perception
  chart: oci://ghcr.io/openads-project/lanelet2_object_list_prediction/helm/lanelet2-object-list-prediction
  version: 1.0.2-main
  condition: profileGroups.perception.enabled
  values: [openadstack/understanding/lanelet2_object_list_prediction/lanelet2-object-list-prediction-perception/values.yaml.gotmpl]
