name: Helmfile

on:
  push:
    branches:
      - main
      - k8s # TODO: Remove when k8s branch is merged into main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  generate:
    name: Helmfile
    uses: openads-project/openads-helm/.github/workflows/helmfile-oci.yml@feature/helmfile # TODO: Change to main branch when merged
    with:
      compose-file: docker-compose.yml
      env-file: .env
      include-env-file-in-bundle: true
      chart-map: deployment/chart-map.yaml
      profiles: carla,traffic,automated-testing,no-perception,planning
      active-profiles-only: false
      output-dir: deployment/generated
      helmfile-entrypoint: deployment/helmfile.yaml
      bundle-dir: deployment
      artifact-name: openadsim-helmfile
